// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace abcRetail.Models;

public partial class InventoryTransaction
{
    [Key]
    public int TransactionID { get; set; }

    public int ProductID { get; set; }

    [Required]
    [StringLength(50)]
    public string ChangeType { get; set; }

    public int QuantityChange { get; set; }

    public DateTime? TransactionDate { get; set; }

    [ForeignKey("ProductID")]
    public virtual Product Product { get; set; }
}