// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace abcRetail.Models;

[Table("MessagesLog")]
public partial class MessagesLog
{
    [Key]
    public int MessageID { get; set; }

    public int? OrderID { get; set; }

    [StringLength(100)]
    public string MessageType { get; set; }

    public string Payload { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    public DateTime? CreatedDate { get; set; }

    [ForeignKey("OrderID")]
    [InverseProperty("MessagesLogs")]
    public virtual Order Order { get; set; }
}